### ISSUE TITLE
Can't find docs about .disk

### ISSUE THREAD

**Issue by Nakilon** [threez/ruby-vmstat#21]
Had to look into code to find out how it works.

**Comment by threez** [comment]
You can find the YARD documentation here: http://www.rubydoc.info/gems/vmstat/Vmstat/Snapshot

**Comment by Nakilon** [comment]
It says `.disks` but I had to use `.disk("/")`.

**Comment by threez** [comment]
If you don't use the snapshot API you can find the doc here: http://www.rubydoc.info/gems/vmstat/Vmstat#disk-class_method
