### ISSUE TITLE
Calculate used memory percentage

### ISSUE THREAD

**Issue by jonnynux** [threez/ruby-vmstat#24]
Hi,
I'm going crazy trying to calculate used memory percentage. Vmstat gives me the following infos:
```
 pagesize=4096,
 wired=206705,
 active=1840031,
 inactive=1979580,
 free=80112,
 pageins=7268181,
 pageouts=122914456
```
But top gives me 16425712 total,   320760 free,  2994884 used. used / total * 100 gives 18% used.

Any suggestion?

Thank you,
Gjergji

**Comment by threez** [comment]
Hi, sry for late reply but top does a different calculation depending on the OS, ruby-vmstat does the same calculation on all OS does that help?

**Comment by jonnynux** [comment]
Ok. So to calculate the used percentage I did: (wired + active) / (wired + active + inactive + free) * 100.
Is that correct?

**Comment by threez** [comment]
It depends on what you want so way, I know that is not helpful ;-). If you are on linux you may want to use `available` to check on the available memory, on most other operating systems you may want to `((wired + active + inactive).to_f / total) * 100.0` to get use memory or use `(free.to_f / total) * 100.0` for free.

**Comment by jonnynux** [comment]
Ok, thank you very much.
