### ISSUE TITLE
Test on 2.3.1

### ISSUE THREAD

**Issue by connorshea** [threez/ruby-vmstat#8]
I don't know if 2.3.1 with OS X works on Travis, but since we'd like to upgrade to Ruby 2.3 at GitLab it'd be nice to know vmstat supports 2.3 :)

Alternatively, use a matrix and only test it on Linux?

**Comment by threez** [comment]
The problem was/is that there is no rvm binary package available for os x yet. They turn that flag on by default. The linux worker had no problems as the code doesn't have. I will have a look at the matix exclusion.

**Comment by threez** [comment]
Doing this is actually kind of hard. I'm using ruby-head right now, since it should be [supported](http://rubies.travis-ci.org) but even that doesn't work...

**Comment by threez** [comment]
im running the tests against head now.
